---
- name: SWAP用ファイルの作成
  shell: dd if=/dev/zero of=/swap.extended bs=1M count={{ SWAP_SIZE }}
  become: yes
  args:
    creates: /swap.extended
  register: result

- name: ファイルの権限変更
  file:
    path: /swap.extended
    mode: '0600'
  become: yes

- name: ファイルをSWAP化
  shell: mkswap /swap.extended
  become: yes
  when: result is changed

- name: SWAP領域として有効化
  shell: swapon /swap.extended
  become: yes
  when: result is changed

- name: swapをマウントする
  mount:
    name: swap
    src: /swap.extended
    fstype: swap
    opts: defaults
    passno: '0'
    dump: '0'
    state: present
